zookeeper:
  image: jplock/zookeeper
  ports: 
    - "127.0.0.1:2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.1.1-1
  ports:
    - "127.0.0.1:9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
